### ISSUE TITLE
latest version error on py3.7: " 'LTP' object has no attribute 'seg'"

### ISSUE THREAD

**Issue by angeleyeKJ** [HIT-SCIR/ltp#581]
I'm working on a project based on python 3.7. After creating a new conda env with 3.7, I did 'pip install ltp' and got:

> _Successfully installed charset-normalizer-2.1.1 colorama-0.4.5 filelock-3.8.0 huggingface-hub-0.9.1 idna-3.3 importlib-metadata-4.12.0 ltp-4.2.7 ltp-core-0.1.1 ltp-extension-0.1.6 numpy-1.21.6 packaging-21.3 pyparsing-3.0.9 pyyaml-6.0 regex-2022.8.17 requests-2.28.1 tokenizers-0.12.1 torch-1.12.1 tqdm-4.64.0 transformers-4.21.2 typing-extensions-4.3.0 urllib3-1.26.12 zipp-3.8.1_

Then I tried (from [quickstart guide](https://ltp.readthedocs.io/zh_CN/latest/))

> from ltp import LTP
> ltp = LTP()
> segment, _ = ltp.seg(["他叫汤姆去拿外衣。"])

and got

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\txt\lib\site-packages\torch\nn\modules\module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'LTP' object has no attribute 'seg'

**Comment by yjiezh** [comment]
+1，same issue，'LTP' object has no attribute 'seg' on py3.9

**Comment by AlongWY** [comment]
API做了一些修改，现在是pipeline的api

**Comment by Zomun** [comment]
+1，same issue，'LTP' object has no attribute 'seg' on py3.7 ubantu22.04;pipeline是指？

**Comment by AlongWY** [comment]
```python
cws, pos, ner = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner"]).to_tuple()
```

**Comment by Zomun** [comment]
thanks
